# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Npm@1
  displayName: 'install'
  inputs:
    command: 'install'
- task: Npm@1
  displayName: 'build'
  inputs:
    command: custom
    customCommand: run build
- task: Npm@1
  displayName: 'lint'
  inputs:
    command: 'custom'
    customCommand: 'run lint'
- task: Npm@1
  displayName: 'test'
  inputs:
    command: 'custom'
    customCommand: 'run test-once'
- task: PublishBuildArtifacts@1
  displayName: 'publish'
  inputs:
    PathtoPublish: public
    ArtifactName: public
